server:
    port: 4425

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # RUTA PARA SERVICIO DE CATÁLOGO
        - id:  service-catalogo
          uri: http://localhost:4419
          predicates:
          - Path=/api/v1/categorias/**, /api/v1/productos/**
        # RUTA PARA SERVICIO DE INVENTARIO
        - id: service-inventario
          uri: http://localhost:4421
          predicates:
          - Path=/api/v1/movimiento-inventario/**, /api/v1/stock/**
        # RUTA PARA SERVICIO DE VENTAS
        - id: service-ventas
          uri: http://localhost:4422
          predicates:
          - Path=/api/v1/ordenes/**, /api/v1/detalles/**
        # RUTA PARA SERVICIO DE PAGOS
        - id: service-pagos
          uri: http://localhost:4423
          predicates:
          - Path=/api/v1/pago/**, /api/v1/metodos-pago/**
        # RITA PARA SERVICIO DE CLIENTES
        - id: service-clientes
          uri: http://localhost:4420
          predicates:
          - Path=/api/v1/clientes/**

        # RUTA PARA SERVICIO DE FACTURAS
        - id: service-facturacion
          uri: http://localhost:4426
          predicates:
          - Path=/api/v1/facturas/**
            
