spring.application.name=service-reportes

server.port=4429

spring.datasource.url=jdbc:mysql://localhost:3306/bd_reportes
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
