spring.application.name=service_proveedores
spring.datasource.url=jdbc:mysql://localhost:3306/bd_proveedores
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=4427