spring.application.name=service-pagos

spring.datasource.url=jdbc:mysql://localhost:3306/bd_pago
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=4423
flow.api-key=50B0EFBC-BF0E-4783-8E08-7F9CF8CLF3EC
flow.secret-key=e2bf5b21f8c27cdd65a04fdaa492de7cca7d8887

flow.base-url=https://sandbox.flow.cl/api